### ISSUE TITLE
SectionRecess crashes on build123d 0.10 ShapeList boolean results

### ISSUE THREAD

**Issue by pzfreo** [pzfreo/quiddity#505]
## Delivery status — 2026-09-05

Fix implemented in **#506**, now targeting main after #504 merged (`ce5ebf8`). The public reproduction and 67 support/channel/corner tests pass independently on build123d 0.9.1, 0.10.0 and 0.11.1; the new pinned-version CI is green. Full PR validation and merge are still pending. No fixed Quiddity release is published yet; Draftwright must retain its current production pin until one is explicitly released. This issue stays open until the fix lands.

## Consumer blocker

Draftwright's SectionRecess migration (pzfreo/draftwright#1471) fails before consumer adaptation with released Quiddity 0.2.0 on its supported Python 3.10/build123d 0.10 combination. The same pocket corpus and adapter pass with Python 3.14/build123d 0.11.

## Minimal public reproduction

```python
from build123d import Box, Pos
from quiddity import build_section_recess_document

part = Box(100, 60, 20) - Pos(22, -11, 7) * Box(30, 12, 6)
document = build_section_recess_document(part)
```

Under Python 3.10 and build123d 0.10 this raises:

```text
AttributeError: 'ShapeList' object has no attribute 'area'
```

The failure is in `_open_channel_section._supports`, reached through the ordinary aggregate's corner-recess publication. After `uncovered = uncovered.cut(graph.face(node))`, the code assumes a single shape and reads `uncovered.area`. The supported older build123d API returns a `ShapeList`. Subsequent support subtraction also needs to handle multiple remaining fragments, not merely sum an initial result's area.

The reproduction uses only public provider entry points and constructed geometry. The old pinned b123d-recognisers 0.4.14 recognises one pocket on this part.

## Measured consumer impact

On Draftwright's 10-case independently authored pocket STEP corpus, the migration module reports **47 passed / 14 setup errors** with Python 3.10. The errors cover lone, equal, opposed, side-opening, disconnected-compound and topology-variant pockets. The same module reports **61 passed** on Python 3.14. The production dependency remains pinned; the candidate provider is development-only, and the migration branch must not merge or switch production until this compatibility failure is resolved.

## Required fix and evidence

- Handle empty, single and fragmented boolean results across supported build123d versions while retaining the physical support proof.
- Preserve the union/subtraction logic: overlapping supports must not be double-counted, and holes or uncovered fragments must not produce a false complete-support claim.
- Add a public-entry regression for the minimal pocket on build123d 0.10 and 0.11.
- Keep negative/partial-support and split-face cases in the regression set.
- Publish the fix in an immutable Quiddity release so Draftwright can update its exact pin.

No consumer-private import, topology rescan, exception-swallowing fallback or forced build123d 0.11 upgrade is proposed.

**Comment by pzfreo** [comment]
Fix is in #506, stacked on CLI PR #504. Confirmed the released 0.2.0 crash on Python 3.10/build123d 0.10.0. The fix retains all fragments and subtracts later supports from each, preserving the complete-support test. All 67 support/channel/corner regressions pass on 0.9.1, 0.10.0 and 0.11.1 in isolated installed-provider environments. A three-version CI workflow is included. Not merged or released yet; Draftwright should retain its current production pin until an immutable fixed release is available.

**Comment by pzfreo** [comment]
Released in Quiddity 0.2.1: https://pypi.org/project/quiddity/0.2.1/ . Trusted publication run 34001341361 succeeded from tag quiddity-v0.2.1 at 70e5047612c085b1311e2b74972b28c88bf97052. Verified a clean PyPI install outside the repo on Python 3.10/build123d 0.10.0: the exact public reproduction above produces occurrences without error. Draftwright can now evaluate updating its immutable provider pin; no consumer changes were made here.
